finnhub.api.key=d6aaai1r01qqjvbpmd2gd6aaai1r01qqjvbpmd30

spring.datasource.url=jdbc:h2:mem:tradecore
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console